// GENERATED by scripts/prepare-images.mjs — do not edit by hand.
// Run `node scripts/prepare-images.mjs` after changing a crop.
export interface PhotoAsset {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
  alt: string;
  sizes: ReadonlyArray<{ src: string; width: number }>;
}

export const PHOTOS: Record<string, PhotoAsset> = {
  "hero-thali": {
    "src": "/images/hero-thali-1024.webp",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwAgCdASoMAAwAAwBSJbACdAYtLuKwWdZmsaSgAP7ybRMl2+tsFfb2DMKPV7c9AbwMh/+TPnFbm2rpQIGIoy2iGnOFqaohBN9YQqMcdWdtrRP7Wn5QNp+3h3apGjy6AAA=",
    "alt": "A brass puja thali laid with marigolds, kumkum, rice, a lit diya and incense on ivory linen",
    "sizes": [
      {
        "src": "/images/hero-thali-1024.webp",
        "width": 1024
      },
      {
        "src": "/images/hero-thali-640.webp",
        "width": 640
      }
    ]
  },
  "hero-thali-wide": {
    "src": "/images/hero-thali-wide-1024.webp",
    "width": 1024,
    "height": 600,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMAAcAAwBSJbACdAYrxajOYzTAAP7Kqzkdt8sbBKWD4cPNT9O278GMPB4tlAtvRXhVVPGCmjUitY0FUZ/+TpGyJgo7IOW6guO65/PAAAA=",
    "alt": "A brass puja thali arranged with ritual essentials",
    "sizes": [
      {
        "src": "/images/hero-thali-wide-1024.webp",
        "width": 1024
      }
    ]
  },
  "story-ganesh": {
    "src": "/images/story-ganesh-1024.webp",
    "width": 1024,
    "height": 620,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoMAAcAAwBSJbACdAEedWzDYpgAAMtM/JQ8/FGyVSJIfiMQc1IJEKdlahYnxDn9CVg7tWD41yj5klroRTxQdqlm/zzXewq7RRfzVQpK6sQm8AAA",
    "alt": "A clay Ganesha idol garlanded with marigolds beside a coconut, modak and incense",
    "sizes": [
      {
        "src": "/images/story-ganesh-1024.webp",
        "width": 1024
      }
    ]
  },
  "og-default": {
    "src": "/images/og-default-1024.webp",
    "width": 1024,
    "height": 536,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMAAYAAwBSJbACdAD8LiprrhwA/rhCpx6ruxNeabK9PLLj/rdnnO3KIrU0PYmCajip9nH+j4Tv/B7xh/WX0rFZx39/rFlxhRiq3PAAAAA=",
    "alt": "POOJARO — Every Ritual. Everything You Need.",
    "sizes": [
      {
        "src": "/images/og-default-1024.webp",
        "width": 1024
      }
    ]
  },
  "kit-ganesh": {
    "src": "/images/kit-ganesh-1024.webp",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMAAwAAwBSJbACdAEWgaidRlMJiwAA+OTvtHd0KYrs0mUHDWlshiT2ZWyizLCPsxIDMAxxpDrXls7j9ZLaBltiDnWZJ6URqr0LIBJF+1SnwK7Te1D6AoXveAAAAA==",
    "alt": "Ganesh Puja Kit — a garlanded clay Ganesha idol with coconut, modak, kumkum and durva grass",
    "sizes": [
      {
        "src": "/images/kit-ganesh-1024.webp",
        "width": 1024
      },
      {
        "src": "/images/kit-ganesh-640.webp",
        "width": 640
      }
    ]
  },
  "kit-lakshmi": {
    "src": "/images/kit-lakshmi-640.webp",
    "width": 640,
    "height": 636,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoMAAwAAwBSJbACdAYsFajhQQAAAPZwwMtfdxVoxeehKmSjM6Y7vYev3H6LCM1GSfnbGOMMaDbIbLXwuQVc7/FsrA/JZ1MkaEh7BhCHYZijm82+UEMR1r0K8HSAAA==",
    "alt": "Lakshmi Puja Kit — a brass thali of haldi and kumkum ringed by Lakshmi coins, lit diyas and a betel leaf",
    "sizes": [
      {
        "src": "/images/kit-lakshmi-640.webp",
        "width": 640
      }
    ]
  },
  "kit-satyanarayan": {
    "src": "/images/kit-satyanarayan-1024.webp",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMAAwAAwBSJbACdAEWgaidRlMJiwAA+OTvtHd0KYrs0mUHDWlshiT2ZWyizLCPsxIDMAxxpDrXls7j9ZLaBltiDnWZJ6URqr0LIBJF+1SnwK7Te1D6AoXveAAAAA==",
    "alt": "Satyanarayan Puja Kit — traditional chowki setup with brass thali, panchamrit, tulsi, banana leaves, and sacred samagri",
    "sizes": [
      {
        "src": "/images/kit-satyanarayan-1024.webp",
        "width": 1024
      }
    ]
  },
  "kit-shiv": {
    "src": "/images/kit-shiv-1024.webp",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMAAwAAwBSJbACdAEWgaidRlMJiwAA+OTvtHd0KYrs0mUHDWlshiT2ZWyizLCPsxIDMAxxpDrXls7j9ZLaBltiDnWZJ6URqr0LIBJF+1SnwK7Te1D6AoXveAAAAA==",
    "alt": "Shiv Puja Kit — brass Shivling, bilva patra, panchamrit lota, white chandan, and vibhuti",
    "sizes": [
      {
        "src": "/images/kit-shiv-1024.webp",
        "width": 1024
      }
    ]
  },
  "kit-durga": {
    "src": "/images/kit-durga-1024.webp",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMAAwAAwBSJbACdAEWgaidRlMJiwAA+OTvtHd0KYrs0mUHDWlshiT2ZWyizLCPsxIDMAxxpDrXls7j9ZLaBltiDnWZJ6URqr0LIBJF+1SnwK7Te1D6AoXveAAAAA==",
    "alt": "Durga Puja Kit — red chunri, sindoor pot, copper kalash with coconut, and hibiscus offerings",
    "sizes": [
      {
        "src": "/images/kit-durga-1024.webp",
        "width": 1024
      }
    ]
  },
  "kit-navratri": {
    "src": "/images/kit-navratri-1024.webp",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMAAwAAwBSJbACdAEWgaidRlMJiwAA+OTvtHd0KYrs0mUHDWlshiT2ZWyizLCPsxIDMAxxpDrXls7j9ZLaBltiDnWZJ6URqr0LIBJF+1SnwK7Te1D6AoXveAAAAA==",
    "alt": "Navratri Akhand Jyot Kit — brass akhand diya lamp with glass chimney, desi ghee, and continuous wicks",
    "sizes": [
      {
        "src": "/images/kit-navratri-1024.webp",
        "width": 1024
      }
    ]
  },
  "kit-havan": {
    "src": "/images/kit-havan-1024.webp",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMAAwAAwBSJbACdAEWgaidRlMJiwAA+OTvtHd0KYrs0mUHDWlshiT2ZWyizLCPsxIDMAxxpDrXls7j9ZLaBltiDnWZJ6URqr0LIBJF+1SnwK7Te1D6AoXveAAAAA==",
    "alt": "Havan Samagri Kit — copper havan kund, herbal samagri mix, mango wood samidha, and pure desi cow ghee",
    "sizes": [
      {
        "src": "/images/kit-havan-1024.webp",
        "width": 1024
      }
    ]
  },
  "sam-cotton-wicks": {
    "src": "/images/sam-cotton-wicks-1024.webp",
    "width": 1024,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMAAwAAwBSJbACdAEWgaidRlMJiwAA+OTvtHd0KYrs0mUHDWlshiT2ZWyizLCPsxIDMAxxpDrXls7j9ZLaBltiDnWZJ6URqr0LIBJF+1SnwK7Te1D6AoXveAAAAA==",
    "alt": "Pure cotton round and long wicks for diyas and akhand jyot",
    "sizes": [
      {
        "src": "/images/sam-cotton-wicks-1024.webp",
        "width": 1024
      }
    ]
  },
  "kit-griha-pravesh": {
    "src": "/images/kit-griha-pravesh-680.webp",
    "width": 680,
    "height": 590,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoMAAoAAwBSJaACdAECpq7zLxo2QAAA+QWFwPBxpDv12knyoZaYR3GP/skTnf2oe4/E1yGYDaJrsv+JMKaiADqwEzdj1+/ri5wHopjfdLDJuC+IWAAAAA==",
    "alt": "Griha Pravesh Puja Kit — a compartment tray of labelled kumkum, haldi and akshat vials with clay diyas, dhoop and kalawa",
    "sizes": [
      {
        "src": "/images/kit-griha-pravesh-680.webp",
        "width": 680
      },
      {
        "src": "/images/kit-griha-pravesh-640.webp",
        "width": 640
      }
    ]
  },
  "kit-lakshmi-lotus": {
    "src": "/images/kit-lakshmi-lotus-430.webp",
    "width": 430,
    "height": 430,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQAgCdASoMAAwAAwBSJbACdAYrna//4dhROwAA/bYFNrkQf8jOgpNF+fUlDv2dAqF2E75NYYReQun+9eZP5r01WZoHPpMq3oTmH0ONy2oMpo34jJhJNVommezRYRkE7tdDaXeTjkK1z0DzmNcz5/OZ8M4AAA==",
    "alt": "Pink lotus blooms on leaf pads beside a marigold garland",
    "sizes": [
      {
        "src": "/images/kit-lakshmi-lotus-430.webp",
        "width": 430
      }
    ]
  },
  "sam-marigold": {
    "src": "/images/sam-marigold-272.webp",
    "width": 272,
    "height": 272,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwAgCdASoMAAwAAwBSJbACdLoAEJKWOlIFzW7QAP5sMkvXOYQQVuNHXBmR5+TikxVWzg3oIRep32ByTe7mjYn2EpzRhU3NeV0zPr/yd1REIRBbo//nCToFRQS9xC15f1v+W/i5cxDp+y4/VmwAAA==",
    "alt": "A brass bowl heaped with orange and yellow marigold blooms and loose petals",
    "sizes": [
      {
        "src": "/images/sam-marigold-272.webp",
        "width": 272
      }
    ]
  },
  "sam-kumkum": {
    "src": "/images/sam-kumkum-268.webp",
    "width": 268,
    "height": 268,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoMAAwAAwBSJbACdAEWtesjsnY+AAD+0p3X/h5TNhgIv3hGTmkWChv5QebXlPurxcmgMBAZ66JXCUeaU6y8oDmwQ+0rdG90vcAD+AWugY5KHXG7M/rnCTb8YS2JreQQgAA=",
    "alt": "A scalloped brass bowl of deep red kumkum powder",
    "sizes": [
      {
        "src": "/images/sam-kumkum-268.webp",
        "width": 268
      }
    ]
  },
  "sam-incense": {
    "src": "/images/sam-incense-336.webp",
    "width": 336,
    "height": 356,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoMAA0AAwBSJagCdAEO52dYg0AA/t/npE5mQ3V9JUPYrVsa7gRw8stXsZAdY+kG5dYV9VH3Bp3lfdyCI14NAvINym6eEAAA",
    "alt": "Incense sticks fanned in a small brass stand with smoke rising",
    "sizes": [
      {
        "src": "/images/sam-incense-336.webp",
        "width": 336
      }
    ]
  },
  "sam-diya-brass": {
    "src": "/images/sam-diya-brass-304.webp",
    "width": 304,
    "height": 296,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoMAAwAAwBSJbACdAYstqcnmM9fb7AA+wUMUSqcglziS5omPpMkBYMv4qCW4I7DCsq2TCGw6JHeqCHtjgHZmVu1RQGeidjLUHIv+MA6uPya+xeRpwUvEev4pi7p6tNSAAA=",
    "alt": "A lit brass diya with a steady flame on an engraved thali",
    "sizes": [
      {
        "src": "/images/sam-diya-brass-304.webp",
        "width": 304
      }
    ]
  },
  "sam-akshat": {
    "src": "/images/sam-akshat-268.webp",
    "width": 268,
    "height": 262,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAgCdASoMAAwAAwBSJbACdLoAAw8xCXaJBJgAAP22441GFapxXK2Ymd1ZGDZ70RinpgpmdCHDaxQgZRJpg1+nQiVwwH0GgmddBmAxkBxUkVvXpgZbUtJ8BkKlWcAA",
    "alt": "A brass bowl of raw white akshat rice",
    "sizes": [
      {
        "src": "/images/sam-akshat-268.webp",
        "width": 268
      }
    ]
  },
  "sam-chandan": {
    "src": "/images/sam-chandan-306.webp",
    "width": 306,
    "height": 258,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoMAAoAAwBSJbACdAC90NSGQgAA9nOO++Rxcnbtn787+JulG+f8XSSI11Pfzqjbx4ydHRB56frfi7guqhW+xpTzTzFPuuXBbHNmxt5FiqlQAA==",
    "alt": "Ground sandalwood chandan paste in a brass bowl with a wooden applicator",
    "sizes": [
      {
        "src": "/images/sam-chandan-306.webp",
        "width": 306
      }
    ]
  },
  "sam-thali-spoon": {
    "src": "/images/sam-thali-spoon-404.webp",
    "width": 404,
    "height": 306,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoMAAkAAwBSJbACdADYC1QAAP40S5SD1T2wvPr1Vn58geizroFQsMWknUoxEHI9oOlR0vrdRCq43tQT5MEzmH8SjzrJEbV+8jno7XAA",
    "alt": "An engraved brass thali rim with an ornate brass offering spoon",
    "sizes": [
      {
        "src": "/images/sam-thali-spoon-404.webp",
        "width": 404
      }
    ]
  },
  "sam-supari": {
    "src": "/images/sam-supari-292.webp",
    "width": 292,
    "height": 262,
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoMAAsAAwBSJbACdAYpH2tlKpU+OgAA/sJO6IvjGYoZmxIMOXVgwUQrRU0k9mGZAhrJ3QoxhAWHGls3zZldWP7CqVQ3KRm4mRJFj63Ud/HHseKO0tzU38YS2Ouo9WOAAAA=",
    "alt": "A brass bowl of marigold blooms and whole nutmeg on a puja thali",
    "sizes": [
      {
        "src": "/images/sam-supari-292.webp",
        "width": 292
      }
    ]
  },
  "sam-coins": {
    "src": "/images/sam-coins-500.webp",
    "width": 500,
    "height": 200,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAUAAwBSJbACdAEers1wleAA/uDZSu7wW2WIWj07Mfh5fGsZlB1M85k8K8o9tMoNceDgA8KitaX+FIAAAA==",
    "alt": "A row of embossed golden Lakshmi coins on ivory linen",
    "sizes": [
      {
        "src": "/images/sam-coins-500.webp",
        "width": 500
      }
    ]
  },
  "sam-diya-clay": {
    "src": "/images/sam-diya-clay-288.webp",
    "width": 288,
    "height": 360,
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQAgCdASoMAA8AAwBSJbACdLoAAnSiOhodA6gA/QKDH/NqFdKqdlREAWbNZ+gF94Y9LXULHvS8DFBPGIPWirfLlRhc5qb89DatZjjmumXwh3IzVye7GzOcEOblGA0J5L0TKP/X06zHJpfepYUKLdvhS9AAAA==",
    "alt": "Lit terracotta clay diyas with cotton wicks",
    "sizes": [
      {
        "src": "/images/sam-diya-clay-288.webp",
        "width": 288
      }
    ]
  },
  "sam-haldi": {
    "src": "/images/sam-haldi-380.webp",
    "width": 380,
    "height": 280,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoMAAkAAwBSJbACdG1/AkK9gm2AAP5IwaSlgxGdfn/iUM5pPv9CLPjPCmPT1CnrCZ0i1PvtOsvTo799w/UUy2eqwzRf3HZvob+QPdQdkrqeYGG3dLA16yGhd10XboAA",
    "alt": "Brass bowls of turmeric haldi and red kumkum with brass spoons on a thali",
    "sizes": [
      {
        "src": "/images/sam-haldi-380.webp",
        "width": 380
      }
    ]
  },
  "sam-mishri": {
    "src": "/images/sam-mishri-220.webp",
    "width": 220,
    "height": 180,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAAoAAwBSJQBOgCPw5l1mUcAA/urrNUqbrXSGlXIND4aiTgy3u+W5Fv6wTx/aIV/T35aS+5SZBZO8QAA=",
    "alt": "Crystallised mishri sugar in a small brass dish",
    "sizes": [
      {
        "src": "/images/sam-mishri-220.webp",
        "width": 220
      }
    ]
  },
  "sam-paan": {
    "src": "/images/sam-paan-340.webp",
    "width": 340,
    "height": 260,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoMAAkAAwBSJaACdAYq1a+qSPZSoAD5EWc9uZfEa+NldepdQ7fl2QadoPQSL3YID/PCH7tiLvO7WKDqnhaU0EevVKjr4A7uIAA=",
    "alt": "A glossy green betel paan leaf with whole nutmeg",
    "sizes": [
      {
        "src": "/images/sam-paan-340.webp",
        "width": 340
      }
    ]
  },
  "sam-garland": {
    "src": "/images/sam-garland-240.webp",
    "width": 240,
    "height": 780,
    "blurDataURL": "data:image/webp;base64,UklGRiwBAABXRUJQVlA4ICABAABQBgCdASoMACcAPtlYpEyoJSOiNVgIAQAbCWwAnTKEf22gHo1kSAHbhXbKvowSBJa/N1ZdV44CPMJeAAD+ZDQTqAwXx27B7X6cEtRbm9Ujt1l5Dm8Eo0xDEBiq72IstfBaPc1Ov2dNIPfc02ltWhFAJrPtJmICSrJ7wesdzwtzNq+YeWEnqctxfM5noF0/bkH4PNtqBP/jmA4mRKuaycwLYxl3fKD7e7kj2ZskHmOIVk7I8cCgCAuMwpZZrzTckYDhgBTK0Ufh3BqGUN46j+lHCrqAR5uNFWRgb2W8s5TyMsKSHQAhntGrGnlD7t7wL/9GGH1EfUZV9qqHf6cg9krNb1yaweE9aBVoFCJxDu8S71bWfd6BMTlmCF07ndsggAA=",
    "alt": "A long marigold garland of orange and yellow blooms strung with leaves",
    "sizes": [
      {
        "src": "/images/sam-garland-240.webp",
        "width": 240
      }
    ]
  },
  "sam-incense-stand": {
    "src": "/images/sam-incense-stand-224.webp",
    "width": 224,
    "height": 300,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQAgCdASoMABAAAwBSJaACdAdwB4ZLP5WvYAAA+XjAM7/HGoUAh2f5uidCDQn93j+C0q2Ddia9+Aw32LMQlbaH3Wi4ZTwTstFXZ9tI/esYWf9IG/Du2FjQRzedVPnuFiU4iwPHa6i35oWisea5aThgAAA=",
    "alt": "Incense sticks in a footed brass stand beside a lit clay diya",
    "sizes": [
      {
        "src": "/images/sam-incense-stand-224.webp",
        "width": 224
      }
    ]
  },
  "sam-kalash": {
    "src": "/images/sam-kalash-260.webp",
    "width": 260,
    "height": 400,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACwBACdASoMABIAPt1apkyopSOiMAgBEBuJbACdMoR3ACsFftBzeHAmdDOP4ggAAOHrbaoV3imPxFk1bOfFlNcOi4Aio5zTxLATbo/q2hhWY0aeJnq8OCFZvD5+w4cTB2MGj9cY+o9rgPdQDsBx/JcKeHvu6SmI6JfOjIrdOhXxMblG1hwLtWFu4BVh+Pz+i18/0NgSTsD/5/obAk2LmcaP1NawAA==",
    "alt": "A whole coconut resting on banana leaves in a copper kalash",
    "sizes": [
      {
        "src": "/images/sam-kalash-260.webp",
        "width": 260
      }
    ]
  },
  "sam-modak": {
    "src": "/images/sam-modak-400.webp",
    "width": 400,
    "height": 290,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoMAAkAAwBSJagCdADdpKTVdAAA/Z1Iic9JYTpeus05/fF5ffOziCAhyy5jdEUiZfV+D6NXk+VIN00DsaDn2xKhgI6gLBfNuRe2iZRsa+SsgAAA",
    "alt": "Saffron-topped modak arranged on a silver plate with pistachio",
    "sizes": [
      {
        "src": "/images/sam-modak-400.webp",
        "width": 400
      }
    ]
  },
  "sam-durva": {
    "src": "/images/sam-durva-300.webp",
    "width": 300,
    "height": 220,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoMAAkAAwBSJbACdAELh0uQkJhgAP7veMvvwF8JIK25F5PIhE9tSbL302kgW2sNQl3UVkTMBznVXWSI2zcoHOuprhMiuJFAAAA=",
    "alt": "A fresh bundle of durva grass beside marigold petals",
    "sizes": [
      {
        "src": "/images/sam-durva-300.webp",
        "width": 300
      }
    ]
  },
  "sam-sindoor": {
    "src": "/images/sam-sindoor-260.webp",
    "width": 260,
    "height": 200,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoMAAkAAwBSJbACdAEX6Se5JAAA/iYp7ZBs4PANSl8A53beJCjcT9heYpC0uJckCedoWNm1vxc8CRMI1B/4N9gGJK5xc/BF3oX59WOYJjIAAA==",
    "alt": "A copper bowl of bright red sindoor with a wooden spoon",
    "sizes": [
      {
        "src": "/images/sam-sindoor-260.webp",
        "width": 260
      }
    ]
  },
  "sam-idol": {
    "src": "/images/sam-idol-330.webp",
    "width": 330,
    "height": 520,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABwBACdASoMABMAPt1apkyopSOiMAgBEBuJbACdMoR3AdBk1n9s0C0hU0Iq0AD83Om7KvB8/lfmKnB6CfUehr38in8ZEDNspHFoUqAlUsYhw/VC9mzCN6U0afaKE5BalocP1CfKhsPAjdeU4QqmxM40Vn5vQj+H/bqm2yJ79robuDaNphGimYNih2ecjc5mLVkDjLl4YPjs7utwkNuIAAAA",
    "alt": "A terracotta Ganesha idol draped in a marigold garland",
    "sizes": [
      {
        "src": "/images/sam-idol-330.webp",
        "width": 330
      }
    ]
  },
  "sam-vials": {
    "src": "/images/sam-vials-380.webp",
    "width": 380,
    "height": 230,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoMAAcAAwBSJaACdADZlgtAAN0HuWhN5Q5INQ3PYoWSop5xhu7IaHAcXMaZuBqqZtSkjP1LheEumU/9qmMOoYqQJ1ZaiP8gAAA=",
    "alt": "Glass vials of kumkum, haldi and akshat with printed labels and silver caps",
    "sizes": [
      {
        "src": "/images/sam-vials-380.webp",
        "width": 380
      }
    ]
  },
  "sam-dhoop": {
    "src": "/images/sam-dhoop-200.webp",
    "width": 200,
    "height": 400,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBACdASoMABgAPt1apkyopSOiMAgBEBuJYgCdMoAvQBXLpuztKdKRD7F6CAD+tZjDc3E4c5Hz4h/V67+mjGvAElbPQFX8AE0IL+L95D57L7sCYQvDZATloj5ZcvoQTy1qSliBgrPkroGP8U9FNXdh5wFaaNZ1bfZs89S/AH8Xdz/s0HOw/AmAchg6QORsVMkQYAAA",
    "alt": "A bundle of dhoop sticks packed in a kraft tray compartment",
    "sizes": [
      {
        "src": "/images/sam-dhoop-200.webp",
        "width": 200
      }
    ]
  },
  "sam-kalawa": {
    "src": "/images/sam-kalawa-230.webp",
    "width": 230,
    "height": 300,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQAgCdASoMABAAAwBSJbACdAEU7/gIQbwAAP7xItadJLNsDg/Tmk9XvF1KjByj42MDRQF9RZpn0UGwNC7cw+dIloVp/0bc5ObHi8z6TPXyHmnN0hpHju3Mxp1Cat/7Duc2bvl4fLNS3XNhAN7AAA==",
    "alt": "A skein of red and yellow kalawa thread",
    "sizes": [
      {
        "src": "/images/sam-kalawa-230.webp",
        "width": 230
      }
    ]
  },
  "sam-diya-row": {
    "src": "/images/sam-diya-row-420.webp",
    "width": 420,
    "height": 200,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMAAYAAwBSJZgCdADdLt57HoAAzju7XI6S2t9c1A1BPi9gVuWA3+r0P36U4ZFjtQKNN++qNQeOc0zl5XbeDZIpmgastoDq3gAAAA==",
    "alt": "Three painted terracotta diyas with cotton wicks in a kit tray",
    "sizes": [
      {
        "src": "/images/sam-diya-row-420.webp",
        "width": 420
      }
    ]
  },
  "sam-camphor": {
    "src": "/images/sam-camphor-210.webp",
    "width": 210,
    "height": 130,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoMAAcAAwBSJZgCdAEfUXFV6QAA/f01vkypZgEaFFnZNFr5OyD7dOeosdfb7rUWVKjMf8zKdLp2Y6TFsEZLlXHwbkbfLdBrvSlEAAAA",
    "alt": "White camphor tablets in a small wooden box",
    "sizes": [
      {
        "src": "/images/sam-camphor-210.webp",
        "width": 210
      }
    ]
  }
};

export type PhotoKey = keyof typeof PHOTOS;

export function photo(key: string): PhotoAsset | null {
  return PHOTOS[key] ?? null;
}

export function isKnownPhoto(key: string): key is PhotoKey {
  return Object.prototype.hasOwnProperty.call(PHOTOS, key);
}
