import { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'POOJARO',
    short_name: 'POOJARO',
    description: 'Premium Indian Puja Samagri & Ritual Kits',
    start_url: '/',
    display: 'standalone',
    background_color: '#FAF8F3', // bg-ivory
    theme_color: '#3A2118', // text-brown
    icons: [
      // Both generated by scripts/make-icons.mjs. The 512 is listed twice
      // because Next's Manifest type takes one purpose per entry, not the
      // spec's space-separated form — and the diya sits inside Android's 80%
      // safe zone, so the same file works masked with nothing cropped off.
      {
        src: '/icon-192x192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
