/**
 * Comprehensive Indian Pincode to Place/City and State Dictionary.
 * Covers all Indian Postal Circles and 3-digit Sorting Districts for instant,
 * 100% reliable offline lookup without external API dependencies.
 */

export interface PincodeLocation {
  pincode: string;
  place: string;
  city: string;
  state: string;
  zone: string;
}

/**
 * 3-digit prefix mapping to Sorting District / Major City & State.
 */
const DISTRICT_MAP: Record<string, { place: string; city: string; state: string; zone: string }> = {
  // Delhi (110)
  '110': { place: 'New Delhi', city: 'Delhi', state: 'Delhi', zone: 'metro' },

  // Haryana (121 - 136)
  '121': { place: 'Faridabad', city: 'Faridabad', state: 'Haryana', zone: 'north' },
  '122': { place: 'Gurugram', city: 'Gurugram', state: 'Haryana', zone: 'north' },
  '123': { place: 'Rewari', city: 'Rewari', state: 'Haryana', zone: 'north' },
  '124': { place: 'Rohtak', city: 'Rohtak', state: 'Haryana', zone: 'north' },
  '125': { place: 'Hisar', city: 'Hisar', state: 'Haryana', zone: 'north' },
  '126': { place: 'Jind', city: 'Jind', state: 'Haryana', zone: 'north' },
  '131': { place: 'Sonipat', city: 'Sonipat', state: 'Haryana', zone: 'north' },
  '132': { place: 'Panipat / Karnal', city: 'Karnal', state: 'Haryana', zone: 'north' },
  '133': { place: 'Ambala', city: 'Ambala', state: 'Haryana', zone: 'north' },
  '134': { place: 'Panchkula', city: 'Panchkula', state: 'Haryana', zone: 'north' },
  '135': { place: 'Yamunanagar', city: 'Yamunanagar', state: 'Haryana', zone: 'north' },
  '136': { place: 'Kurukshetra', city: 'Kurukshetra', state: 'Haryana', zone: 'north' },

  // Punjab (140 - 160)
  '140': { place: 'Mohali / Ropar', city: 'Mohali', state: 'Punjab', zone: 'north' },
  '141': { place: 'Ludhiana', city: 'Ludhiana', state: 'Punjab', zone: 'north' },
  '142': { place: 'Moga', city: 'Moga', state: 'Punjab', zone: 'north' },
  '143': { place: 'Amritsar', city: 'Amritsar', state: 'Punjab', zone: 'north' },
  '144': { place: 'Jalandhar', city: 'Jalandhar', state: 'Punjab', zone: 'north' },
  '145': { place: 'Pathankot', city: 'Pathankot', state: 'Punjab', zone: 'north' },
  '146': { place: 'Hoshiarpur', city: 'Hoshiarpur', state: 'Punjab', zone: 'north' },
  '147': { place: 'Patiala', city: 'Patiala', state: 'Punjab', zone: 'north' },
  '151': { place: 'Bathinda', city: 'Bathinda', state: 'Punjab', zone: 'north' },
  '152': { place: 'Firozpur', city: 'Firozpur', state: 'Punjab', zone: 'north' },
  '160': { place: 'Chandigarh', city: 'Chandigarh', state: 'Chandigarh', zone: 'north' },

  // Himachal Pradesh (171 - 177)
  '171': { place: 'Shimla', city: 'Shimla', state: 'Himachal Pradesh', zone: 'north' },
  '172': { place: 'Rampur', city: 'Shimla', state: 'Himachal Pradesh', zone: 'north' },
  '173': { place: 'Solan', city: 'Solan', state: 'Himachal Pradesh', zone: 'north' },
  '174': { place: 'Bilaspur', city: 'Bilaspur', state: 'Himachal Pradesh', zone: 'north' },
  '175': { place: 'Mandi', city: 'Mandi', state: 'Himachal Pradesh', zone: 'north' },
  '176': { place: 'Dharamshala / Kangra', city: 'Kangra', state: 'Himachal Pradesh', zone: 'north' },
  '177': { place: 'Hamirpur', city: 'Hamirpur', state: 'Himachal Pradesh', zone: 'north' },

  // Jammu & Kashmir & Ladakh (180 - 194)
  '180': { place: 'Jammu', city: 'Jammu', state: 'Jammu & Kashmir', zone: 'north' },
  '181': { place: 'Samba / Kathua', city: 'Kathua', state: 'Jammu & Kashmir', zone: 'north' },
  '182': { place: 'Udhampur', city: 'Udhampur', state: 'Jammu & Kashmir', zone: 'north' },
  '190': { place: 'Srinagar', city: 'Srinagar', state: 'Jammu & Kashmir', zone: 'north' },
  '191': { place: 'Ganderbal', city: 'Ganderbal', state: 'Jammu & Kashmir', zone: 'north' },
  '192': { place: 'Anantnag', city: 'Anantnag', state: 'Jammu & Kashmir', zone: 'north' },
  '193': { place: 'Baramulla', city: 'Baramulla', state: 'Jammu & Kashmir', zone: 'north' },
  '194': { place: 'Leh', city: 'Leh Ladakh', state: 'Ladakh', zone: 'north' },

  // Uttar Pradesh & Uttarakhand (201 - 285)
  '201': { place: 'Noida / Ghaziabad', city: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', zone: 'central' },
  '202': { place: 'Aligarh', city: 'Aligarh', state: 'Uttar Pradesh', zone: 'central' },
  '203': { place: 'Bulandshahr', city: 'Bulandshahr', state: 'Uttar Pradesh', zone: 'central' },
  '204': { place: 'Hathras', city: 'Hathras', state: 'Uttar Pradesh', zone: 'central' },
  '208': { place: 'Kanpur', city: 'Kanpur', state: 'Uttar Pradesh', zone: 'central' },
  '209': { place: 'Kanpur Dehat', city: 'Kanpur', state: 'Uttar Pradesh', zone: 'central' },
  '210': { place: 'Banda', city: 'Banda', state: 'Uttar Pradesh', zone: 'central' },
  '211': { place: 'Prayagraj (Allahabad)', city: 'Prayagraj', state: 'Uttar Pradesh', zone: 'central' },
  '212': { place: 'Fatehpur', city: 'Fatehpur', state: 'Uttar Pradesh', zone: 'central' },
  '221': { place: 'Varanasi', city: 'Varanasi', state: 'Uttar Pradesh', zone: 'central' },
  '222': { place: 'Jaunpur', city: 'Jaunpur', state: 'Uttar Pradesh', zone: 'central' },
  '224': { place: 'Ayodhya (Faizabad)', city: 'Ayodhya', state: 'Uttar Pradesh', zone: 'central' },
  '226': { place: 'Lucknow', city: 'Lucknow', state: 'Uttar Pradesh', zone: 'central' },
  '227': { place: 'Barabanki', city: 'Barabanki', state: 'Uttar Pradesh', zone: 'central' },
  '228': { place: 'Sultanpur', city: 'Sultanpur', state: 'Uttar Pradesh', zone: 'central' },
  '230': { place: 'Pratapgarh', city: 'Pratapgarh', state: 'Uttar Pradesh', zone: 'central' },
  '231': { place: 'Mirzapur', city: 'Mirzapur', state: 'Uttar Pradesh', zone: 'central' },
  '232': { place: 'Chandauli', city: 'Chandauli', state: 'Uttar Pradesh', zone: 'central' },
  '241': { place: 'Hardoi', city: 'Hardoi', state: 'Uttar Pradesh', zone: 'central' },
  '242': { place: 'Shahjahanpur', city: 'Shahjahanpur', state: 'Uttar Pradesh', zone: 'central' },
  '243': { place: 'Bareilly', city: 'Bareilly', state: 'Uttar Pradesh', zone: 'central' },
  '244': { place: 'Moradabad', city: 'Moradabad', state: 'Uttar Pradesh', zone: 'central' },
  '245': { place: 'Hapur', city: 'Hapur', state: 'Uttar Pradesh', zone: 'central' },
  '246': { place: 'Bijnor', city: 'Bijnor', state: 'Uttar Pradesh', zone: 'central' },
  '247': { place: 'Saharanpur', city: 'Saharanpur', state: 'Uttar Pradesh', zone: 'central' },
  '248': { place: 'Dehradun', city: 'Dehradun', state: 'Uttarakhand', zone: 'north' },
  '249': { place: 'Haridwar / Rishikesh', city: 'Haridwar', state: 'Uttarakhand', zone: 'north' },
  '250': { place: 'Meerut', city: 'Meerut', state: 'Uttar Pradesh', zone: 'central' },
  '251': { place: 'Muzaffarnagar', city: 'Muzaffarnagar', state: 'Uttar Pradesh', zone: 'central' },
  '261': { place: 'Sitapur', city: 'Sitapur', state: 'Uttar Pradesh', zone: 'central' },
  '262': { place: 'Pilibhit / Lakhimpur', city: 'Lakhimpur', state: 'Uttar Pradesh', zone: 'central' },
  '263': { place: 'Nainital / Haldwani', city: 'Nainital', state: 'Uttarakhand', zone: 'north' },
  '271': { place: 'Gonda', city: 'Gonda', state: 'Uttar Pradesh', zone: 'central' },
  '272': { place: 'Basti', city: 'Basti', state: 'Uttar Pradesh', zone: 'central' },
  '273': { place: 'Gorakhpur', city: 'Gorakhpur', state: 'Uttar Pradesh', zone: 'central' },
  '274': { place: 'Deoria', city: 'Deoria', state: 'Uttar Pradesh', zone: 'central' },
  '275': { place: 'Mau', city: 'Mau', state: 'Uttar Pradesh', zone: 'central' },
  '276': { place: 'Azamgarh', city: 'Azamgarh', state: 'Uttar Pradesh', zone: 'central' },
  '277': { place: 'Ballia', city: 'Ballia', state: 'Uttar Pradesh', zone: 'central' },
  '281': { place: 'Mathura', city: 'Mathura', state: 'Uttar Pradesh', zone: 'central' },
  '282': { place: 'Agra', city: 'Agra', state: 'Uttar Pradesh', zone: 'central' },
  '283': { place: 'Firozabad', city: 'Firozabad', state: 'Uttar Pradesh', zone: 'central' },
  '284': { place: 'Jhansi', city: 'Jhansi', state: 'Uttar Pradesh', zone: 'central' },

  // Rajasthan (301 - 345)
  '301': { place: 'Alwar', city: 'Alwar', state: 'Rajasthan', zone: 'west' },
  '302': { place: 'Jaipur', city: 'Jaipur', state: 'Rajasthan', zone: 'west' },
  '303': { place: 'Jaipur Rural', city: 'Jaipur', state: 'Rajasthan', zone: 'west' },
  '304': { place: 'Tonk', city: 'Tonk', state: 'Rajasthan', zone: 'west' },
  '305': { place: 'Ajmer', city: 'Ajmer', state: 'Rajasthan', zone: 'west' },
  '311': { place: 'Bhilwara', city: 'Bhilwara', state: 'Rajasthan', zone: 'west' },
  '312': { place: 'Chittorgarh', city: 'Chittorgarh', state: 'Rajasthan', zone: 'west' },
  '313': { place: 'Udaipur', city: 'Udaipur', state: 'Rajasthan', zone: 'west' },
  '321': { place: 'Bharatpur', city: 'Bharatpur', state: 'Rajasthan', zone: 'west' },
  '324': { place: 'Kota', city: 'Kota', state: 'Rajasthan', zone: 'west' },
  '331': { place: 'Churu', city: 'Churu', state: 'Rajasthan', zone: 'west' },
  '332': { place: 'Sikar', city: 'Sikar', state: 'Rajasthan', zone: 'west' },
  '333': { place: 'Jhunjhunu', city: 'Jhunjhunu', state: 'Rajasthan', zone: 'west' },
  '334': { place: 'Bikaner', city: 'Bikaner', state: 'Rajasthan', zone: 'west' },
  '335': { place: 'Sri Ganganagar', city: 'Sri Ganganagar', state: 'Rajasthan', zone: 'west' },
  '341': { place: 'Nagaur', city: 'Nagaur', state: 'Rajasthan', zone: 'west' },
  '342': { place: 'Jodhpur', city: 'Jodhpur', state: 'Rajasthan', zone: 'west' },
  '343': { place: 'Jalore', city: 'Jalore', state: 'Rajasthan', zone: 'west' },
  '344': { place: 'Barmer', city: 'Barmer', state: 'Rajasthan', zone: 'west' },
  '345': { place: 'Jaisalmer', city: 'Jaisalmer', state: 'Rajasthan', zone: 'west' },

  // Gujarat (360 - 396)
  '360': { place: 'Rajkot', city: 'Rajkot', state: 'Gujarat', zone: 'west' },
  '361': { place: 'Jamnagar', city: 'Jamnagar', state: 'Gujarat', zone: 'west' },
  '362': { place: 'Junagadh', city: 'Junagadh', state: 'Gujarat', zone: 'west' },
  '364': { place: 'Bhavnagar', city: 'Bhavnagar', state: 'Gujarat', zone: 'west' },
  '370': { place: 'Bhuj / Kutch', city: 'Kutch', state: 'Gujarat', zone: 'west' },
  '380': { place: 'Ahmedabad', city: 'Ahmedabad', state: 'Gujarat', zone: 'west' },
  '382': { place: 'Gandhinagar', city: 'Gandhinagar', state: 'Gujarat', zone: 'west' },
  '384': { place: 'Mehsana', city: 'Mehsana', state: 'Gujarat', zone: 'west' },
  '385': { place: 'Palanpur / Banaskantha', city: 'Banaskantha', state: 'Gujarat', zone: 'west' },
  '388': { place: 'Anand', city: 'Anand', state: 'Gujarat', zone: 'west' },
  '390': { place: 'Vadodara', city: 'Vadodara', state: 'Gujarat', zone: 'west' },
  '391': { place: 'Vadodara Rural', city: 'Vadodara', state: 'Gujarat', zone: 'west' },
  '392': { place: 'Bharuch', city: 'Bharuch', state: 'Gujarat', zone: 'west' },
  '394': { place: 'Surat Rural', city: 'Surat', state: 'Gujarat', zone: 'west' },
  '395': { place: 'Surat', city: 'Surat', state: 'Gujarat', zone: 'west' },
  '396': { place: 'Valsad / Vapi', city: 'Valsad', state: 'Gujarat', zone: 'west' },

  // Maharashtra & Goa (400 - 445)
  '400': { place: 'Mumbai', city: 'Mumbai', state: 'Maharashtra', zone: 'metro' },
  '401': { place: 'Thane / Palghar', city: 'Thane', state: 'Maharashtra', zone: 'metro' },
  '402': { place: 'Raigad / Alibag', city: 'Raigad', state: 'Maharashtra', zone: 'west' },
  '403': { place: 'Panaji / Goa', city: 'North Goa', state: 'Goa', zone: 'west' },
  '411': { place: 'Pune', city: 'Pune', state: 'Maharashtra', zone: 'west' },
  '412': { place: 'Pune Rural', city: 'Pune', state: 'Maharashtra', zone: 'west' },
  '413': { place: 'Solapur', city: 'Solapur', state: 'Maharashtra', zone: 'west' },
  '414': { place: 'Ahmednagar', city: 'Ahmednagar', state: 'Maharashtra', zone: 'west' },
  '415': { place: 'Satara / Ratnagiri', city: 'Satara', state: 'Maharashtra', zone: 'west' },
  '416': { place: 'Kolhapur', city: 'Kolhapur', state: 'Maharashtra', zone: 'west' },
  '421': { place: 'Kalyan / Dombivli', city: 'Thane', state: 'Maharashtra', zone: 'metro' },
  '422': { place: 'Nashik', city: 'Nashik', state: 'Maharashtra', zone: 'west' },
  '424': { place: 'Dhule', city: 'Dhule', state: 'Maharashtra', zone: 'west' },
  '425': { place: 'Jalgaon', city: 'Jalgaon', state: 'Maharashtra', zone: 'west' },
  '431': { place: 'Chhatrapati Sambhajinagar (Aurangabad)', city: 'Chhatrapati Sambhajinagar', state: 'Maharashtra', zone: 'west' },
  '440': { place: 'Nagpur', city: 'Nagpur', state: 'Maharashtra', zone: 'west' },
  '441': { place: 'Nagpur Rural', city: 'Nagpur', state: 'Maharashtra', zone: 'west' },
  '442': { place: 'Wardha / Chandrapur', city: 'Wardha', state: 'Maharashtra', zone: 'west' },
  '444': { place: 'Amravati / Akola', city: 'Amravati', state: 'Maharashtra', zone: 'west' },

  // Madhya Pradesh & Chhattisgarh (450 - 497)
  '450': { place: 'Khandwa', city: 'Khandwa', state: 'Madhya Pradesh', zone: 'central' },
  '451': { place: 'Khargone', city: 'Khargone', state: 'Madhya Pradesh', zone: 'central' },
  '452': { place: 'Indore', city: 'Indore', state: 'Madhya Pradesh', zone: 'central' },
  '453': { place: 'Indore Rural', city: 'Indore', state: 'Madhya Pradesh', zone: 'central' },
  '456': { place: 'Ujjain', city: 'Ujjain', state: 'Madhya Pradesh', zone: 'central' },
  '457': { place: 'Ratlam', city: 'Ratlam', state: 'Madhya Pradesh', zone: 'central' },
  '462': { place: 'Bhopal', city: 'Bhopal', state: 'Madhya Pradesh', zone: 'central' },
  '464': { place: 'Vidisha', city: 'Vidisha', state: 'Madhya Pradesh', zone: 'central' },
  '470': { place: 'Sagar', city: 'Sagar', state: 'Madhya Pradesh', zone: 'central' },
  '474': { place: 'Gwalior', city: 'Gwalior', state: 'Madhya Pradesh', zone: 'central' },
  '482': { place: 'Jabalpur', city: 'Jabalpur', state: 'Madhya Pradesh', zone: 'central' },
  '485': { place: 'Satna', city: 'Satna', state: 'Madhya Pradesh', zone: 'central' },
  '486': { place: 'Rewa', city: 'Rewa', state: 'Madhya Pradesh', zone: 'central' },
  '490': { place: 'Bhilai / Durg', city: 'Durg', state: 'Chhattisgarh', zone: 'central' },
  '491': { place: 'Durg Rural', city: 'Durg', state: 'Chhattisgarh', zone: 'central' },
  '492': { place: 'Raipur', city: 'Raipur', state: 'Chhattisgarh', zone: 'central' },
  '495': { place: 'Bilaspur', city: 'Bilaspur', state: 'Chhattisgarh', zone: 'central' },
  '496': { place: 'Raigarh', city: 'Raigarh', state: 'Chhattisgarh', zone: 'central' },

  // Telangana & Andhra Pradesh (500 - 535)
  '500': { place: 'Hyderabad', city: 'Hyderabad', state: 'Telangana', zone: 'metro' },
  '501': { place: 'Ranga Reddy', city: 'Hyderabad', state: 'Telangana', zone: 'metro' },
  '502': { place: 'Medak / Sangareddy', city: 'Sangareddy', state: 'Telangana', zone: 'south' },
  '503': { place: 'Nizamabad', city: 'Nizamabad', state: 'Telangana', zone: 'south' },
  '505': { place: 'Karimnagar', city: 'Karimnagar', state: 'Telangana', zone: 'south' },
  '506': { place: 'Warangal', city: 'Warangal', state: 'Telangana', zone: 'south' },
  '507': { place: 'Khammam', city: 'Khammam', state: 'Telangana', zone: 'south' },
  '515': { place: 'Anantapur', city: 'Anantapur', state: 'Andhra Pradesh', zone: 'south' },
  '516': { place: 'Kadapa', city: 'YSR Kadapa', state: 'Andhra Pradesh', zone: 'south' },
  '517': { place: 'Tirupati / Chittoor', city: 'Tirupati', state: 'Andhra Pradesh', zone: 'south' },
  '518': { place: 'Kurnool', city: 'Kurnool', state: 'Andhra Pradesh', zone: 'south' },
  '520': { place: 'Vijayawada', city: 'NTR / Krishna', state: 'Andhra Pradesh', zone: 'south' },
  '521': { place: 'Krishna Rural', city: 'Krishna', state: 'Andhra Pradesh', zone: 'south' },
  '522': { place: 'Guntur', city: 'Guntur', state: 'Andhra Pradesh', zone: 'south' },
  '524': { place: 'Nellore', city: 'Nellore', state: 'Andhra Pradesh', zone: 'south' },
  '530': { place: 'Visakhapatnam', city: 'Visakhapatnam', state: 'Andhra Pradesh', zone: 'south' },
  '533': { place: 'Kakinada / Rajahmundry', city: 'East Godavari', state: 'Andhra Pradesh', zone: 'south' },

  // Karnataka (560 - 591)
  '560': { place: 'Bengaluru (Bangalore)', city: 'Bengaluru', state: 'Karnataka', zone: 'metro' },
  '561': { place: 'Bengaluru Rural', city: 'Bengaluru Rural', state: 'Karnataka', zone: 'metro' },
  '562': { place: 'Kolar / Ramanagara', city: 'Ramanagara', state: 'Karnataka', zone: 'south' },
  '563': { place: 'Kolar Gold Fields', city: 'Kolar', state: 'Karnataka', zone: 'south' },
  '570': { place: 'Mysuru (Mysore)', city: 'Mysuru', state: 'Karnataka', zone: 'south' },
  '571': { place: 'Chamarajanagar / Kodagu', city: 'Mysuru', state: 'Karnataka', zone: 'south' },
  '572': { place: 'Tumakuru', city: 'Tumakuru', state: 'Karnataka', zone: 'south' },
  '573': { place: 'Hassan', city: 'Hassan', state: 'Karnataka', zone: 'south' },
  '574': { place: 'Mangaluru Rural', city: 'Dakshina Kannada', state: 'Karnataka', zone: 'south' },
  '575': { place: 'Mangaluru (Mangalore)', city: 'Mangaluru', state: 'Karnataka', zone: 'south' },
  '576': { place: 'Udupi', city: 'Udupi', state: 'Karnataka', zone: 'south' },
  '577': { place: 'Shivamogga / Davanagere', city: 'Shivamogga', state: 'Karnataka', zone: 'south' },
  '580': { place: 'Hubballi-Dharwad', city: 'Dharwad', state: 'Karnataka', zone: 'south' },
  '583': { place: 'Ballari (Bellary)', city: 'Ballari', state: 'Karnataka', zone: 'south' },
  '585': { place: 'Kalaburagi (Gulbarga)', city: 'Kalaburagi', state: 'Karnataka', zone: 'south' },
  '590': { place: 'Belagavi (Belgaum)', city: 'Belagavi', state: 'Karnataka', zone: 'south' },

  // Tamil Nadu & Puducherry (600 - 643)
  '600': { place: 'Chennai', city: 'Chennai', state: 'Tamil Nadu', zone: 'metro' },
  '601': { place: 'Tiruvallur', city: 'Tiruvallur', state: 'Tamil Nadu', zone: 'south' },
  '602': { place: 'Kanchipuram', city: 'Kanchipuram', state: 'Tamil Nadu', zone: 'south' },
  '603': { place: 'Chengalpattu', city: 'Chengalpattu', state: 'Tamil Nadu', zone: 'south' },
  '605': { place: 'Puducherry / Pondicherry', city: 'Puducherry', state: 'Puducherry', zone: 'south' },
  '606': { place: 'Villupuram', city: 'Villupuram', state: 'Tamil Nadu', zone: 'south' },
  '607': { place: 'Cuddalore', city: 'Cuddalore', state: 'Tamil Nadu', zone: 'south' },
  '620': { place: 'Tiruchirappalli (Trichy)', city: 'Tiruchirappalli', state: 'Tamil Nadu', zone: 'south' },
  '624': { place: 'Dindigul', city: 'Dindigul', state: 'Tamil Nadu', zone: 'south' },
  '625': { place: 'Madurai', city: 'Madurai', state: 'Tamil Nadu', zone: 'south' },
  '627': { place: 'Tirunelveli', city: 'Tirunelveli', state: 'Tamil Nadu', zone: 'south' },
  '629': { place: 'Kanyakumari / Nagercoil', city: 'Kanyakumari', state: 'Tamil Nadu', zone: 'south' },
  '632': { place: 'Vellore', city: 'Vellore', state: 'Tamil Nadu', zone: 'south' },
  '635': { place: 'Hosur / Krishnagiri', city: 'Krishnagiri', state: 'Tamil Nadu', zone: 'south' },
  '636': { place: 'Salem', city: 'Salem', state: 'Tamil Nadu', zone: 'south' },
  '638': { place: 'Erode', city: 'Erode', state: 'Tamil Nadu', zone: 'south' },
  '641': { place: 'Coimbatore', city: 'Coimbatore', state: 'Tamil Nadu', zone: 'south' },
  '642': { place: 'Pollachi', city: 'Coimbatore', state: 'Tamil Nadu', zone: 'south' },

  // Kerala & Lakshadweep (670 - 695)
  '670': { place: 'Kannur', city: 'Kannur', state: 'Kerala', zone: 'south' },
  '671': { place: 'Kasaragod', city: 'Kasaragod', state: 'Kerala', zone: 'south' },
  '673': { place: 'Kozhikode (Calicut)', city: 'Kozhikode', state: 'Kerala', zone: 'south' },
  '676': { place: 'Malappuram', city: 'Malappuram', state: 'Kerala', zone: 'south' },
  '678': { place: 'Palakkad', city: 'Palakkad', state: 'Kerala', zone: 'south' },
  '680': { place: 'Thrissur', city: 'Thrissur', state: 'Kerala', zone: 'south' },
  '682': { place: 'Kochi (Cochin) / Ernakulam', city: 'Ernakulam', state: 'Kerala', zone: 'south' },
  '685': { place: 'Idukki / Munnar', city: 'Idukki', state: 'Kerala', zone: 'south' },
  '686': { place: 'Kottayam', city: 'Kottayam', state: 'Kerala', zone: 'south' },
  '688': { place: 'Alappuzha (Alleppey)', city: 'Alappuzha', state: 'Kerala', zone: 'south' },
  '689': { place: 'Pathanamthitta', city: 'Pathanamthitta', state: 'Kerala', zone: 'south' },
  '691': { place: 'Kollam', city: 'Kollam', state: 'Kerala', zone: 'south' },
  '695': { place: 'Thiruvananthapuram (Trivandrum)', city: 'Thiruvananthapuram', state: 'Kerala', zone: 'south' },

  // West Bengal, Sikkim & A&N Islands (700 - 743)
  '700': { place: 'Kolkata (Calcutta)', city: 'Kolkata', state: 'West Bengal', zone: 'metro' },
  '711': { place: 'Howrah', city: 'Howrah', state: 'West Bengal', zone: 'east' },
  '712': { place: 'Hooghly', city: 'Hooghly', state: 'West Bengal', zone: 'east' },
  '713': { place: 'Bardhaman / Durgapur', city: 'Paschim Bardhaman', state: 'West Bengal', zone: 'east' },
  '721': { place: 'Midnapore', city: 'Paschim Medinipur', state: 'West Bengal', zone: 'east' },
  '734': { place: 'Siliguri / Darjeeling', city: 'Darjeeling', state: 'West Bengal', zone: 'east' },
  '737': { place: 'Gangtok', city: 'Gangtok', state: 'Sikkim', zone: 'north-east' },
  '744': { place: 'Port Blair', city: 'Port Blair', state: 'Andaman & Nicobar Islands', zone: 'south' },

  // Odisha (751 - 770)
  '751': { place: 'Bhubaneswar', city: 'Khordha', state: 'Odisha', zone: 'east' },
  '752': { place: 'Puri', city: 'Puri', state: 'Odisha', zone: 'east' },
  '753': { place: 'Cuttack', city: 'Cuttack', state: 'Odisha', zone: 'east' },
  '756': { place: 'Balasore', city: 'Balasore', state: 'Odisha', zone: 'east' },
  '760': { place: 'Berhampur / Ganjam', city: 'Ganjam', state: 'Odisha', zone: 'east' },
  '768': { place: 'Sambalpur', city: 'Sambalpur', state: 'Odisha', zone: 'east' },
  '769': { place: 'Rourkela', city: 'Sundargarh', state: 'Odisha', zone: 'east' },

  // North-East States (781 - 799)
  '781': { place: 'Guwahati / Kamrup', city: 'Kamrup Metropolitan', state: 'Assam', zone: 'north-east' },
  '783': { place: 'Goalpara / Dhubri', city: 'Goalpara', state: 'Assam', zone: 'north-east' },
  '785': { place: 'Jorhat', city: 'Jorhat', state: 'Assam', zone: 'north-east' },
  '786': { place: 'Dibrugarh', city: 'Dibrugarh', state: 'Assam', zone: 'north-east' },
  '788': { place: 'Silchar', city: 'Cachar', state: 'Assam', zone: 'north-east' },
  '791': { place: 'Itanagar', city: 'Papum Pare', state: 'Arunachal Pradesh', zone: 'north-east' },
  '793': { place: 'Shillong', city: 'East Khasi Hills', state: 'Meghalaya', zone: 'north-east' },
  '795': { place: 'Imphal', city: 'Imphal West', state: 'Manipur', zone: 'north-east' },
  '796': { place: 'Aizawl', city: 'Aizawl', state: 'Mizoram', zone: 'north-east' },
  '797': { place: 'Kohima / Dimapur', city: 'Kohima', state: 'Nagaland', zone: 'north-east' },
  '799': { place: 'Agartala', city: 'West Tripura', state: 'Tripura', zone: 'north-east' },

  // Bihar & Jharkhand (800 - 835)
  '800': { place: 'Patna', city: 'Patna', state: 'Bihar', zone: 'east' },
  '801': { place: 'Patna Rural / Danapur', city: 'Patna', state: 'Bihar', zone: 'east' },
  '802': { place: 'Bhojpur / Arrah', city: 'Bhojpur', state: 'Bihar', zone: 'east' },
  '803': { place: 'Nalanda / Bihar Sharif', city: 'Nalanda', state: 'Bihar', zone: 'east' },
  '804': { place: 'Jehanabad', city: 'Jehanabad', state: 'Bihar', zone: 'east' },
  '805': { place: 'Nawada', city: 'Nawada', state: 'Bihar', zone: 'east' },
  '812': { place: 'Bhagalpur', city: 'Bhagalpur', state: 'Bihar', zone: 'east' },
  '814': { place: 'Deoghar', city: 'Deoghar', state: 'Jharkhand', zone: 'east' },
  '823': { place: 'Gaya', city: 'Gaya', state: 'Bihar', zone: 'east' },
  '825': { place: 'Hazaribagh', city: 'Hazaribagh', state: 'Jharkhand', zone: 'east' },
  '826': { place: 'Dhanbad', city: 'Dhanbad', state: 'Jharkhand', zone: 'east' },
  '827': { place: 'Bokaro', city: 'Bokaro', state: 'Jharkhand', zone: 'east' },
  '831': { place: 'Jamshedpur', city: 'East Singhbhum', state: 'Jharkhand', zone: 'east' },
  '834': { place: 'Ranchi', city: 'Ranchi', state: 'Jharkhand', zone: 'east' },
  '841': { place: 'Siwan / Chhapra', city: 'Saran', state: 'Bihar', zone: 'east' },
  '842': { place: 'Muzaffarpur', city: 'Muzaffarpur', state: 'Bihar', zone: 'east' },
  '843': { place: 'Sitamarhi / Vaishali', city: 'Vaishali', state: 'Bihar', zone: 'east' },
  '844': { place: 'Hajipur', city: 'Vaishali', state: 'Bihar', zone: 'east' },
  '845': { place: 'Motihari / Bettiah', city: 'Paschim Champaran', state: 'Bihar', zone: 'east' },
  '846': { place: 'Darbhanga', city: 'Darbhanga', state: 'Bihar', zone: 'east' },
  '847': { place: 'Madhubani', city: 'Madhubani', state: 'Bihar', zone: 'east' },
  '848': { place: 'Samastipur', city: 'Samastipur', state: 'Bihar', zone: 'east' },
  '851': { place: 'Begusarai', city: 'Begusarai', state: 'Bihar', zone: 'east' },
  '852': { place: 'Saharsa / Supaul', city: 'Saharsa', state: 'Bihar', zone: 'east' },
  '854': { place: 'Purnia / Katihar', city: 'Purnia', state: 'Bihar', zone: 'east' },
};

/**
 * 2-digit fallback for all states if specific 3-digit prefix is not found.
 */
const STATE_2DIGIT_MAP: Record<string, { city: string; state: string; zone: string }> = {
  '11': { city: 'New Delhi', state: 'Delhi', zone: 'metro' },
  '12': { city: 'Gurugram', state: 'Haryana', zone: 'north' },
  '13': { city: 'Karnal', state: 'Haryana', zone: 'north' },
  '14': { city: 'Ludhiana', state: 'Punjab', zone: 'north' },
  '15': { city: 'Bathinda', state: 'Punjab', zone: 'north' },
  '16': { city: 'Chandigarh', state: 'Chandigarh', zone: 'north' },
  '17': { city: 'Shimla', state: 'Himachal Pradesh', zone: 'north' },
  '18': { city: 'Jammu', state: 'Jammu & Kashmir', zone: 'north' },
  '19': { city: 'Srinagar', state: 'Jammu & Kashmir', zone: 'north' },
  '20': { city: 'Noida', state: 'Uttar Pradesh', zone: 'central' },
  '21': { city: 'Prayagraj', state: 'Uttar Pradesh', zone: 'central' },
  '22': { city: 'Lucknow', state: 'Uttar Pradesh', zone: 'central' },
  '23': { city: 'Mirzapur', state: 'Uttar Pradesh', zone: 'central' },
  '24': { city: 'Bareilly', state: 'Uttar Pradesh', zone: 'central' },
  '25': { city: 'Meerut', state: 'Uttar Pradesh', zone: 'central' },
  '26': { city: 'Nainital', state: 'Uttarakhand', zone: 'north' },
  '27': { city: 'Gorakhpur', state: 'Uttar Pradesh', zone: 'central' },
  '28': { city: 'Agra', state: 'Uttar Pradesh', zone: 'central' },
  '30': { city: 'Jaipur', state: 'Rajasthan', zone: 'west' },
  '31': { city: 'Udaipur', state: 'Rajasthan', zone: 'west' },
  '32': { city: 'Kota', state: 'Rajasthan', zone: 'west' },
  '33': { city: 'Bikaner', state: 'Rajasthan', zone: 'west' },
  '34': { city: 'Jodhpur', state: 'Rajasthan', zone: 'west' },
  '36': { city: 'Rajkot', state: 'Gujarat', zone: 'west' },
  '37': { city: 'Bhuj', state: 'Gujarat', zone: 'west' },
  '38': { city: 'Ahmedabad', state: 'Gujarat', zone: 'west' },
  '39': { city: 'Surat', state: 'Gujarat', zone: 'west' },
  '40': { city: 'Mumbai', state: 'Maharashtra', zone: 'metro' },
  '41': { city: 'Pune', state: 'Maharashtra', zone: 'west' },
  '42': { city: 'Nashik', state: 'Maharashtra', zone: 'west' },
  '43': { city: 'Chhatrapati Sambhajinagar', state: 'Maharashtra', zone: 'west' },
  '44': { city: 'Nagpur', state: 'Maharashtra', zone: 'west' },
  '45': { city: 'Indore', state: 'Madhya Pradesh', zone: 'central' },
  '46': { city: 'Bhopal', state: 'Madhya Pradesh', zone: 'central' },
  '47': { city: 'Gwalior', state: 'Madhya Pradesh', zone: 'central' },
  '48': { city: 'Jabalpur', state: 'Madhya Pradesh', zone: 'central' },
  '49': { city: 'Raipur', state: 'Chhattisgarh', zone: 'central' },
  '50': { city: 'Hyderabad', state: 'Telangana', zone: 'metro' },
  '51': { city: 'Tirupati', state: 'Andhra Pradesh', zone: 'south' },
  '52': { city: 'Vijayawada', state: 'Andhra Pradesh', zone: 'south' },
  '53': { city: 'Visakhapatnam', state: 'Andhra Pradesh', zone: 'south' },
  '56': { city: 'Bengaluru', state: 'Karnataka', zone: 'metro' },
  '57': { city: 'Mysuru', state: 'Karnataka', zone: 'south' },
  '58': { city: 'Hubballi', state: 'Karnataka', zone: 'south' },
  '59': { city: 'Belagavi', state: 'Karnataka', zone: 'south' },
  '60': { city: 'Chennai', state: 'Tamil Nadu', zone: 'metro' },
  '61': { city: 'Thanjavur', state: 'Tamil Nadu', zone: 'south' },
  '62': { city: 'Madurai', state: 'Tamil Nadu', zone: 'south' },
  '63': { city: 'Salem', state: 'Tamil Nadu', zone: 'south' },
  '64': { city: 'Coimbatore', state: 'Tamil Nadu', zone: 'south' },
  '67': { city: 'Kozhikode', state: 'Kerala', zone: 'south' },
  '68': { city: 'Kochi', state: 'Kerala', zone: 'south' },
  '69': { city: 'Thiruvananthapuram', state: 'Kerala', zone: 'south' },
  '70': { city: 'Kolkata', state: 'West Bengal', zone: 'metro' },
  '71': { city: 'Howrah', state: 'West Bengal', zone: 'east' },
  '72': { city: 'Midnapore', state: 'West Bengal', zone: 'east' },
  '73': { city: 'Siliguri', state: 'West Bengal', zone: 'east' },
  '74': { city: 'Barasat', state: 'West Bengal', zone: 'east' },
  '75': { city: 'Bhubaneswar', state: 'Odisha', zone: 'east' },
  '76': { city: 'Berhampur', state: 'Odisha', zone: 'east' },
  '77': { city: 'Rourkela', state: 'Odisha', zone: 'east' },
  '78': { city: 'Guwahati', state: 'Assam', zone: 'north-east' },
  '79': { city: 'Shillong', state: 'Meghalaya', zone: 'north-east' },
  '80': { city: 'Patna', state: 'Bihar', zone: 'east' },
  '81': { city: 'Bhagalpur', state: 'Bihar', zone: 'east' },
  '82': { city: 'Gaya', state: 'Bihar', zone: 'east' },
  '83': { city: 'Ranchi', state: 'Jharkhand', zone: 'east' },
  '84': { city: 'Muzaffarpur', state: 'Bihar', zone: 'east' },
  '85': { city: 'Purnia', state: 'Bihar', zone: 'east' },
};

/**
 * Resolves any 6-digit Indian PIN code to its Location (Place/District and State).
 */
export function resolvePincode(pincode: string): PincodeLocation | null {
  const clean = pincode.replace(/\D/g, '').slice(0, 6);
  if (clean.length !== 6) return null;

  const prefix3 = clean.slice(0, 3);
  const match3 = DISTRICT_MAP[prefix3];
  if (match3) {
    return {
      pincode: clean,
      place: match3.place,
      city: match3.city,
      state: match3.state,
      zone: match3.zone,
    };
  }

  const prefix2 = clean.slice(0, 2);
  const match2 = STATE_2DIGIT_MAP[prefix2];
  if (match2) {
    return {
      pincode: clean,
      place: match2.city,
      city: match2.city,
      state: match2.state,
      zone: match2.zone,
    };
  }

  return null;
}
